"""Fix table names

Revision ID: 20293fa07e91
Revises: 
Create Date: 2025-12-06 02:03:46.683880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20293fa07e91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('case_attendee_UserID_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('case_attendee_CaseID_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'case', ['CaseID'], ['CaseID'])
        batch_op.create_foreign_key(None, 'user', ['UserID'], ['UserID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_attendee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_attendee_CaseID_fkey'), 'case', ['CaseID'], ['CaseID'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('case_attendee_UserID_fkey'), 'user', ['UserID'], ['UserID'], ondelete='CASCADE')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###
