"""Make OldDateID nullable, keep FileAttachment

Revision ID: 35f19afb9efe
Revises: 20293fa07e91
Create Date: 2025-12-06 17:26:34.722420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f19afb9efe'
down_revision = '20293fa07e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_attendee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_attendee_unique'), type_='unique')
        batch_op.drop_constraint(batch_op.f('case_attendee_userid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('case_attendee_caseid_fkey'), type_='foreignkey')

    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.alter_column('OldDateID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.alter_column('OldDateID',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('case_attendee', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('case_attendee_caseid_fkey'), 'case', ['CaseID'], ['CaseID'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('case_attendee_userid_fkey'), 'user', ['UserID'], ['UserID'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('case_attendee_unique'), ['CaseID', 'UserID'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
